### ISSUE TITLE
add reset or rebuild to PropertyTable

### ISSUE THREAD

**Issue by tingspain** [lcaron/opal#47]
I would like to request to add a **reset** or **rebuild method** to the *PropertyTable*, so new object can be assigned to the* PropertyTable*. 

The idea is to use the *PropertyTable* to create a Property view part for Eclipse RCP based on Eclipse 4. The view part will be injected the ESelectionService to update the *PropertyTable* with any change in selection. This part is very easy, however, *PropertyTable* does't provide any reset or reassign methods.

**Comment by lcaron** [comment]
Issue fixed in V1.0.3
