### ISSUE TITLE
Download corrupt?

### ISSUE THREAD

**Issue by vogella** [lcaron/opal#49]
I downloaded the opal-1.0.2-plugin.zip and opal-1.0.3-plugin.jar but cannot unzip it. Are the files corrupt?

**Comment by SolidSyntax** [comment]
I've had the same problem, it seems to be a github issue.
Saving the file by right clicking on the link produces a corrupt file.
But if you open the link (left click) and then select 'View Raw' you get a working file.

**Comment by lcaron** [comment]
Thank you for your feedback, I've fixed the link on the home page, it should be correct now !
