### ISSUE TITLE
ConcurrentModificationException from RoundedToolItem.fireSelectionEvent

### ISSUE THREAD

**Issue by swtdev** [lcaron/opal#51]
This method is unsafe as if a listener decides it's no longer interested and removes itself or adds a new listener then the simple ArrayList being used to store the listeners will fail the comodification check.

At the very least fireSelectionEvent should **clone/copy** the listener list to prevent this, or just use a CopyOnWriteArrayList! :smiley: 

> java.util.ConcurrentModificationException
>     at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
>     at java.util.ArrayList$Itr.next(Unknown Source)
>     at org.mihalis.opal.roundedToolbar.RoundedToolItem.fireSelectionEvent(Unknown Source)
>     at org.mihalis.opal.roundedToolbar.RoundedToolbar$1.handleEvent(Unknown Source)
>     at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
>     at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
>     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
>     at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
>     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
>     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1350)
>     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
>     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1206)
>     at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
>     at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
>     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
>     at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
>     at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)

**Comment by lcaron** [comment]
Fixed by pull request
