### ISSUE TITLE
Angle Slider: setSelection always raise an java.lang.IllegalArgumentException: null soure

### ISSUE THREAD

**Issue by dejawho** [lcaron/opal#54]
Hi, 
AngleSlider has a serious bug  in the setSelecition method. When it fire the selectionListeners it create a new Event(), then this event is used to build a selection event. But a selection event need to have in the passed event the filed widget set, otherwise it will trigger the IllegalAegumentSection. The fix is pretty easy and simple:

```
public void setSelection(final int selection) {
    checkWidget();
    if (selection < 0 || selection > 360) {
        SWT.error(SWT.ERROR_CANNOT_SET_SELECTION);
    }
    this.selection = selection;
    Event e = new Event();
            e.widget = this;
            fireSelectionListeners(e);
    redraw();
}
```

**Comment by lcaron** [comment]
Fix in next release
