### ISSUE TITLE
[Wiki] wrong screenshot for ImageSelector

### ISSUE THREAD

**Issue by rheydenr** [lcaron/opal#55]
Hi all, the screenshot for ImageSelector in this Wiki is wrong (compared to the old version at https://code.google.com/archive/a/eclipselabs.org/p/opal/wikis/ImageSelector.wiki).

Regards
Ralf.

**Comment by lcaron** [comment]
Thank you ralf, problem fixed !

**Comment by rheydenr** [comment]
Great. Can you please update the link to the animation, too? It points to http://opal.eclipselabs.org.codespot.com/hg.wiki/wink/imageSelector.swf which leads to a 404 error page.

**Comment by lcaron** [comment]
Sure, it's done, thank you for your support 👍
