### ISSUE TITLE
Vertical RangeSlider drawVerticalKnob method off by two pixels

### ISSUE THREAD

**Issue by hb91546** [lcaron/opal#59]
Instead of **y + 2** in drawImage invocations, **y + 4** would more precisely place the knob.

Note that drawHorizontalKnob uses **x + 5**.

**Comment by hb91546** [comment]
Note also that methods 
setSelection(final int lowerValue, final int upperValue) 
and
setSelection(final int[] values) 
fail under some circumstances.

more specifically,  when the **new** lowerValue is greater than the **old** upperValue, the **new** lowerValue is rejected.

**Comment by lcaron** [comment]
Fixed in next released
