### ISSUE TITLE
Infinite progress panel on composite

### ISSUE THREAD

**Issue by jimAC2016** [lcaron/opal#63]
Can Infinite progress panel be placed on a composite instead of a shell? My application uses Eclipse RCP for the gui part with different composite part on one screen. All different parts need to load different data and all of them need one Infinite progress panel.

**Comment by lcaron** [comment]
That's an interesting enhancement. I'll create a bug for that !

**Comment by lcaron** [comment]
Fixed in next release (1.0.5). The infinite progress panel can be attached to any composite :)
