### ISSUE TITLE
Access to shell images

### ISSUE THREAD

**Issue by vicenrico** [lcaron/opal#65]
Hello. I love your project but there is a problem for me. I'm using this library into my app, but I would like to change the icon's shell in a few dialogs. I've seen is private. I'm asking if I could access to the shell variable, in order to do shell.setImage(Img). Currently is showing the default icon that I would like to replace for the one of my app.
Thanks in advance

**Comment by lcaron** [comment]
Hi
Thank you for your support and your kind message.
If you're talking about Dialog, you can access to the Shell of the Dialog() using the getShell() method.

I hope I answered your question

Laurent
