### ISSUE TITLE
Access to shell images

### ISSUE THREAD

**Issue by vicenrico** [lcaron/opal#66]
Sorry for opening another post but you closed the previous #65 
What I would like is to change the shell icon for Tipoftheday, and for preferencewindows. You said that with Dialog I can access to the getShell method, but with Tipoftheday and preferencewindow, I can't see this method.
Sorry for being like this, but I like your library and this is very important for me, because I don't want default shell icons in my program.

**Comment by lcaron** [comment]
Hi,
Sorry it was a misunderstanding, I'm gonna fix it today, and prepare a new release !
Laurent

**Comment by lcaron** [comment]
Problem fixed in release V1.0.6
