### ISSUE TITLE
Multichoice access to text widget

### ISSUE THREAD

**Issue by vicenrico** [lcaron/opal#68]
Hello. I'm facing a new situation with this widget. In my program I have a countries list. Is a small one. With the most important countries that are in a database. What I would like is to know how can I set the text field of the widget. I mean, for instance, I get from the db the countries field that are "USA,Spain" (a string field). I don't know how to set the text field with this value, because there is not a setText field like are for a normal combo control. 
I 've digging into the code and I've seen the 
`private void setLabel() ` method

I suppose it would be fine if you developed a 
`public void setLabel(String text)` method in order to initially set the field and have the normal combo control behaviour

**Comment by lcaron** [comment]
Hi,

Can you provide a code snippet ?

Thank you

Laurent

**Comment by vicenrico** [comment]
Well. It implies a lot of classes. I'll try to explain in pseudocode.

I have a db with movies. Each movie has a country field (String field) that is retrieved from db, i.e, (Spain,France).
I don't want to save into db all the countries in the world, so I put only the usual countries (Spain, france, usa, england, italy, and so on).  More or less 30 countries. 
In your control in can select among this 30 countries, but I want the user can enter for instance, Bangladesh and save to db. The next time I get data from the db, I read "Bangladesh" and I want to set Multichoice with this String. I know I can add this country to the control, but what I want is only set the text field with this string and let the selection with the frequent 30 countries.

**Comment by lcaron** [comment]
Bug fixed in release V1.0.7
I added setText() and getText() methods that will hopefully fullfil your needs

**Comment by vicenrico** [comment]
Thank you very much. It's what I was expecting. Many thanks!!!
