### ISSUE TITLE
OSGI bundles for 1.0.5 and 1.0.6 releases are invalid

### ISSUE THREAD

**Issue by mwebber** [lcaron/opal#70]
The OSGI jar for 1.0.5 does not contain any OSGI headers (in `MANIFEST.MF`)
The OSGI jar for 1.0.6 declares itself as `Bundle-Version: 1.0.4` (in `MANIFEST.MF`)

**Comment by lcaron** [comment]
Bug fixed today, thank you for your feeback

**Comment by mwebber** [comment]
Thanks for the prompt fix. 1.0.7 is working for us.
There's one small problem - the download link is wrong. It should be
https://github.com/lcaron/opal/blob/releases/V.1.0.7/opal-1.0.7-plugin.jar?raw=true
The URL includes **`V.1.0.7`** (_not_ `V1.0.7`) - notice the extra **`.`**

**Comment by lcaron** [comment]
Thank you it is fixed
