### ISSUE TITLE
Release URLs not reachable

### ISSUE THREAD

**Issue by SuperOok** [lcaron/opal#71]
The Release links on the main page like https://github.com/lcaron/opal/blob/releases/V1.0.7/opal-1.0.7.jar?raw=true result in a 404.

**Comment by Yakkity** [comment]
The correct URL needs should be

https://github.com/lcaron/opal/blob/releases/V.1.0.7/opal-1.0.7-plugin.jar?raw=true

(note the . after the V)

**Comment by lcaron** [comment]
Problem fixed since 2 minutes. Thank you @SuperOok for the report
