### ISSUE TITLE
PropertyTable unsort() results in error

### ISSUE THREAD

**Issue by morgsie** [lcaron/opal#72]
Hi,
I am trying to call the PropertyTable unsort() from within my code so that I can determine the order in which my properties are displayed in the PropertyTable.

My code looks like this:
		table = new PropertyTable(parent, SWT.NONE);
		table.showButtons();
		table.viewAsCategories();
		table.unsort();

I am getting the following error:
!STACK 0
java.lang.NullPointerException
	at org.mihalis.opal.propertyTable.PTWidgetTree.refillData(Unknown Source)
	at org.mihalis.opal.propertyTable.PropertyTable.unsort(Unknown Source)

Apologies if I am calling this incorrectly, any help would be greatly appreciated.
Thanks in advance!

**Comment by lcaron** [comment]
Issue fixed in Opal 1.0.7

**Comment by morgsie** [comment]
Thank you!
