### ISSUE TITLE
Disabled items in multiselection RoundedToolbar generate SelectionEvents

### ISSUE THREAD

**Issue by swtdev** [lcaron/opal#73]
Hi Laurent,

We have an issue with disabled items in RoundedToolbars unexpectedly generating SelectionEvents. Seems to us that it doesn't make sense for them to do so, no? A disabled item shouldn't generated these when clicked, surely?

You can disable the RoundedToolbar and no SelectionEvents are generated at all. Looks like calling setEnabled on RoundedToolItem only affects the image displayed.

Fix seems simple, RoundedToolbar:136:
`if (item.getBounds().contains(event.x, event.y)) {`
change to:
`if (item.getBounds().contains(event.x, event.y) && item.isEnabled()) {`

Could also move the check inside the if() instead and have it escape the for() loop, as an optimisation.

Thanks,
Justin

**Comment by lcaron** [comment]
Fixed on release 1.0.9, thank you Justin 👍
