### ISSUE TITLE
Provide styles for RoundedToolItem

### ISSUE THREAD

**Issue by dariusz-michura** [lcaron/opal#78]
It would be good if RoundedToolItem supports the same set of styles as org.eclipse.swt.widgets.ToolItem. IMHO at least SWT.PUSH, SWT.CHECK, SWT.RADIO should be supported.

**Comment by lcaron** [comment]
Hi darius,

Nice idea ! 
Can you please fill a bug in bugzilla (because this enhancement will concern Nebula, no longer Opal) ;
https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Nebula
(widget component: other)

Thank you very much

Laurent
