### ISSUE TITLE
Mistaken URL in Wiki  Home Page

### ISSUE THREAD

**Issue by IanMayo** [lcaron/opal#79]
Hi there,
welcome to the Nebula Widgets project :-)

You've a typo in a URL on the Wiki Home Page.  I'd submit a PR, but this isn't possible for Wiki Pages.

Anyway, the URL for Horizontal Spinner points to: https://github.com/lcaron/opal/wiki/Spinner

It should actually point to: https://github.com/lcaron/opal/wiki/HorizontalSpinner

Regards,
Ian

**Comment by lcaron** [comment]
Thank you, the problem has been fixed today !
