### ISSUE TITLE
Button width problem when set timer on dialog

### ISSUE THREAD

**Issue by ckandirali** [lcaron/opal#80]
Hi,
At Opal dialog if I set custom text for buttons and set timer for one of them, text is not fit to the button width and trimmed (**Tekrar Dene** trimmed to **ekrar Dene (2**).  Maybe griddata width can be recalculated after appending (x) .

![2018-03-06 11_05_32-baglanti hatasi](https://user-images.githubusercontent.com/37101396/37020928-af62de6c-212e-11e8-8bcb-d4876f0944d1.png)

Thanks

**Comment by lcaron** [comment]
Hi,
Thank you for opening this report. 
Opal has been merged into Eclipse Nebula, so I filled a bug in Eclipse Bugzilla. This problem will be solved soon on the stable branch of Nebula.

Do you need a patch or will you use Nebula ?

Laurent

**Comment by ckandirali** [comment]
Thanks a lot, I will switch to nebula.

**Comment by lcaron** [comment]
Ok fine, thank you.
